### ISSUE TITLE
Print emulation DCTL

### ISSUE THREAD

**Issue by antonmeleshkevich** [thatcherfreeman/utility-dctls#1]
Hi! Thank you for sharing all of these wonderful tools! Could you please tell a bit about print emulation DCTL? What's logic behind that? I've tried to get it from the code, but my skills in coding are limited to copying/pasting with some modifications.

**Comment by thatcherfreeman** [comment]
<img width="1676" alt="Screen Shot 2022-08-30 at 10 43 16 AM" src="https://user-images.githubusercontent.com/21159194/187507011-72ef229a-0fae-414c-8169-065f66447a1f.png">

Hey great question! Basically that DCTL in particular is intended to replicate an effect I saw in a Cullen Kelly video (and you can somewhat see this if you use Resolve's built-in film emulation LUTs) in which the CMY colors are transformed to be brighter and more saturated than RGB colors. You could see it if you set up a 3D histogram like I have in my screenshot, f(1, 1, 0) > f(1, 0, 0) + f(0, 1, 0) so it skews the shape of the whole 3D cube in an interesting way.

Honestly, I don't think the math I used in this DCTL is based on any physical principles, but it's an interesting operation that doesn't come with Resolve normally.

BTW when making this screenshot, I realized I had some compilation issues with this DCTL because I overloaded the `mix` function. I've posted a fix so you might have to redownload the DCTL if it wasn't doing anything earlier.
