### ISSUE TITLE
Film Grain

### ISSUE THREAD

**Issue by lukeflowers** [thatcherfreeman/utility-dctls#2]
These DCTL's are incredibly useful! I'm having a bit of an issue with the film grain. I'm passing a linear image into two instances of Film Grain and then going from linear back to my working space (DWG) at stock settings the grain is pretty wonky. With some tweaking, I can get some nice results. Do you have any best practice tips or settings you generally use? It is a very beautiful look at the end!

**Comment by thatcherfreeman** [comment]
Good question! NGL I don't really use film grain much myself when I'm coloring, but I did want to set up that DCTL to have some reasonable looking defaults. I think I personally prefer the look of monochrome noise, so that's why I added the Value Noise/Luminance Noise dropdowns. If you're seeing salt and pepper noise or hot speckles, you might have to clamp the input to the DCTL to be >0 to fix that.

If you have any screenshots of what's looking wonky or your settings, please share them and I can see if I can reproduce it

**Comment by lukeflowers** [comment]
Thanks thatcher!

I’m working in DWG and DaVinci Intermediate for my color setup. I’m node based as well. I’m sure it’s something simple.

Here is the node stack

CST DaVinci Int to linear (color space stays the same) > Film Grain (Stock)  > Film Grain (Stock) >CST linear to DaVinci Intermediate. Here is what I’m getting with that setup.

***@***.***

Here it is with grain off.
***@***.***

**Comment by thatcherfreeman** [comment]
I think you're going to have to reply via the github UI on web to attach images, unfortunately

**Comment by lukeflowers** [comment]
Thanks thatcher!
 
I’m working in DWG and DaVinci Intermediate for my color setup. I’m node based as well. I’m sure it’s something simple.
 
Here is the node stack
 
CST DaVinci Int to linear (color space stays the same) > Film Grain (Stock)  > Film Grain (Stock) >CST linear to DaVinci Intermediate. Here is what I’m getting with that setup.
 

 
<img width="592" alt="No Grain" src="https://user-images.githubusercontent.com/128303030/233987679-b7f8722c-8d48-4278-a1af-35343f78a6da.png">
<img width="584" alt="Grain" src="https://user-images.githubusercontent.com/128303030/233987688-b839ae36-46d8-430e-8300-6dafbc2c58a8.png">

**Comment by lukeflowers** [comment]
Hey Thatcher, did the images come through okay on GitHub UI?

Thanks!
Luke Flowers
________________________________

**Comment by thatcherfreeman** [comment]
Thanks for the bump, I totally missed the last message. I'm seeing the images now and that does look problematic. Lemme see if I can reproduce this at stock settings

**Comment by thatcherfreeman** [comment]
Good news Luke! I've been able to reproduce the issue you described and I can't believe that slipped by me. That's what happens when you test your math on exactly one image lol

Here are my findings: 1. You can get dramatically improved results just by changing the default Photon Gain value to 0.5 instead of 0.2. If there's not enough contrast, you could also set both film grain DCTLs to 5.0 DMAX. Additionally, I found that my implementation of monochrome noise had some serious problems that are obvious if you raise the input exposure a lot or bring it down to zero, that weren't present in the RGB noise mode.

As a result, I've updated the default parameters, added a DMIN parameter, and fixed the monochrome noise models in the Film Grain model. Additionally, I added a similar monochrome noise model to the Photon Noise DCTL if you want a noise model that doesn't impact the contrast of your image. Go ahead and redownload those and let me know what you think!

Here are the new default parameters if you want to copy them into the old DCTL (I'd recommend the RGB mode in the old DCTL)
<img width="385" alt="image" src="https://user-images.githubusercontent.com/21159194/234771130-3dd885e5-493b-44f1-be3f-298f6cbb176c.png">

**Comment by lukeflowers** [comment]
Sweet! I'm loving the updates. It really does some nice things to the image! Thanks a ton for your quick work on this. It's a really great grain plugin! The texture that it makes is honestly my favorite I've used.

**Comment by thatcherfreeman** [comment]
Thanks for the feedback! Let me know if you run into any other issues! :)
