### ISSUE TITLE
Film grain DCT clipping values above 1

### ISSUE THREAD

**Issue by ChrisBii** [thatcherfreeman/utility-dctls#3]
Sorry if this is a non-issue.

When doing a CST from log -> Linear
Then placing 2 Film grain DCTLs
Then doing a CST from Linear -> log
Any values above 1 in linear  gets clipped with the DCTLs resulting in loss of any details that went above 1 in Linear.

When stating "pass in a linear image" does that mean LIN (as in scene linear) or is it the display "linear" type as in r709?

I would have thought it to be scene linear, especially with the default activation threshold at 0.18

Hope to get some insight.
Really loving the effect in scene linear (except for the clipped details), while it works "better" in r709 it just doesn't feel as integrated.

**Comment by thatcherfreeman** [comment]
Good question!

Yeah, I'm referring to a scene-linear image as the input, though you could interpret the output of the two DCTLs as display-linear due to the behavior that you're describing. The truth is that film, as a medium, will always be between 0% transmissive and 100% transmissive and that's what results in the output being capped at linear 1.0. If you want, you could apply some gain after the second DCTL to represent the effect of projecting with a lamp brighter than 100 nits.

Another approach you can use is to use my Read Noise and Photon Noise DCTLs to introduce noise into a scene linear image, without rolling off any highlights. I've also found reasonable results by combining read noise with the film noise DCTLs, depending on if you prefer noise in the extreme highlights/shadows, though you may have to clamp off any negatives at certain stages if you run into problems there.

**Comment by ChrisBii** [comment]
Thanks, what a speedy reply!

Makes sense, though I would think that even if film lies between 0-100% transmittance, doing an operation in scene linear will usually push some values above 1.0 with the benefit of being able to pull back those values going from scene linear and back to the native log format (or other CST gamma setting).

While the Photon Noise DCTL does work like you suggest it just, well, doesn't have the same look/feel ;)
It's basically just to complement you on the Film Grain DCTL in general! It may overall one of the best grains I've tried (and I have everything from Filmbox to Dehaner, Filmconvert etc...) If the signal didn't clip when going back to log I would say this would be my no.1 go-to.

Edit: One solution I will try is feeding the film grain DCTL a linear signal below 1.0 and then, as you suggest, pushing the gain after the 2nd DCTL instance.
Edit2: Unfortunately that did not work out.

**Comment by thatcherfreeman** [comment]
Yeah, so strictly speaking the units I chose to use for the output of the film grain DCTL is "transmittance" and that's why it's limited to the 0-1 range. IMO any true emulation of film grain would need to roll off towards a maximum output value that represents a stock with zero density. In your defense though, I think maybe there's room for another version of the tool where perhaps it auto-scales the output in order to maintain some target mid grey value, though that's somewhat less clean from a units standpoint.

In theory, you should be seeing a rolloff towards 1.0 and not a hard clipping, but the output is indeed restricted to the 0-1 range.

Thanks for the kind words though!

**Comment by ChrisBii** [comment]
Thanks again! I do get what you are saying. Maybe that approach would  be better suited for log space? My understanding is that one of the benefits of working in scene linear is to have and retain values above 1.0.
Personally, I would not mind a less accurate grain emulation in this case (if we are working in scene linear).
"any true emulation of film grain would need to roll off towards a maximum output value" - Wouldn't that be possible in scene linear as well? The value would just be somewhere above 1.0? (Sorry, I am in nooo way coding or math inclined, so am just asking stupid questions)

**Comment by thatcherfreeman** [comment]
Well the maximum transmittance of a piece of plastic is 1.0 and those are physically meaningful output units. However, you can adjust what exposure you're sending in, the various parameters in the DCTL, and any gain adjustment you make after the DCTLs. Through a combination of those, it should be possible to roll off at a larger value if you'd like. At some point I had another version of this DCTL or maybe another one where it would automatically scale the output to restore mid grey, which would perhaps make these adjustments a little easier to do.

Imagine you were scanning some film stock. In principle, you're just measuring what proportion of the scanner's backlight made it through the film, for each pixel, and that's what the DCTLs spit out.

Tbh I disagree on the concept that retaining values above 1.0 is the inherent feature of all linear images. IMO the value of linear is that you have a relationship between the code value and some physical quantity of light. In a film system, the maximum amount of light you'll ever see on the screen is fixed at the brightness of the projector's lamp (when the film stock has 100% transmittance), so that's being emulated here and a huge part of the reason I say that we're starting out with Scene Linear and outputting Display linear/transmittance.

**Comment by ChrisBii** [comment]
Thank you for the insights (and all the great DCTLs!)
