### ISSUE TITLE
Saturation Adjustment.dctl

### ISSUE THREAD

**Issue by saulmemeteau** [thatcherfreeman/utility-dctls#4]
Hi Thatcher, first of all thank you so much for this incredible work, it's so valuable. Could you make "Saturation Adjustment DCTL" accessible again? It may be a simple HSV/HSL function but I really like being able to access it from your dctl to play with saturation, simple things are sometimes very useful :-)

**Comment by thatcherfreeman** [comment]
I mostly removed it because Resolve does have a built-in equivalent to that DCTL. Make sure you have something reasonable set for your timeline color space and right click on a node, go to Color Space, and choose HSV or HSL. Then, right click on the node and disable channels 1 and 3 (hue and lum/value), and then apply gamma and/or gain. Should give you the same results.

I would recommend doing the above setup and saving it as a powergrade

**Comment by saulmemeteau** [comment]
It was another quick and easy way to access this function and playing with your dctl slider was really effective!

**Comment by thatcherfreeman** [comment]
well if you _really_ want it, you can always open up the repo at an old commit prior to when I deleted it. [Here it is](https://github.com/thatcherfreeman/utility-dctls/blob/f6dbbf2d8bcc8e0458a0f20e1f78e4b4da7ad117/Utilities/Saturation%20Adjustment.dctl)
