### ISSUE TITLE
T-Log Curve.dctl returns -inf when linear input is 0.0

### ISSUE THREAD

**Issue by antonmeleshkevich** [thatcherfreeman/utility-dctls#5]
Hi! Thank you for sharing all these tools!
I've noticed that T-Log Curve.dctl returns -inf when linear input is 0.0. It for sure can be easily clamped, but is it possible to make it handle the whole positive linear range including 0.0 (or maybe even negatives)? As far as I know, linear 0.0 will always land to negative value if it's encoded as exposure stops.
One example is "Stops 18% gray" curve in Resolve Color Space Transform, that is also a true log encoding curve, that places 10 000 nit (linear 100 value) to 1.0 and linear 0.0 to a slightly negative value. And seems like it doesn't clip the negative values at all.
Another example is ACEScc curve, but while it also places linear 0.0 to a slightly negative value, it has a sort of a toe (not the same as ACEScct of course), that is just normally not visible, because it's in the negative values.
I know T-Log Curve.dctl also doesn't clip values that are very close to 0.0, but slightly positive, and places them as a negative values, which is correct. But it would be really nice if the actual linear 0.0 would be placed somewhere (some correct negative value), instead of returning -inf (which can be seen in Fusion tab).
Is this a matter of few lines or it would require a completely different approach? A a quick hack - to clamp linear input to something like 0.0000001, but maybe there is a better solution to handle this or even the negatives (where useful signal often presented as well, if it's the noisy source).
Thanks!

**Comment by thatcherfreeman** [comment]
Great question! I suppose to compare my T-Log curve with Blackmagic's "Stops 18% Gray", they clamp 0.0 linear as well as negative values to -0.99. My intent with the -inf value was that when a user applies an exposure adjustment in the form of offset, it should not shift 0.0 linear around at all, which I think is a desirable quality. -inf will hopefully remain -inf until you convert back to linear, when we map it back to 0.0.

Now, I think I also see your concern - we often operate with zeros or negative values in our image because the noise floor is often centered at zero. Additionally, I could imagine that some tools you might want to use in the T-Log space may behave poorly when given -inf as input. There are several ways we can address this.

1. I can add some sort of clamping to the linear values that the T-Log curve operates on, perhaps make this clamping parametric, and assign 0.0 linear to say, 1e-10 or something by default.
2. I provide a Clamp.dctl in the Operations folder and you can therefore add your own clamping prior to any tool that needs it.
3. You may have better luck passing the linear image to your tools. Maybe they'll handle negative linear values better than they handle -infinity.
4. Upstream of converting to T-Log, you can apply some sort of gamut mapping (say, a sat v sat curve applied in a polar system like Spherical) to bring all the negative values into the nonnegative domain. This won't solve your complaint with the zeros, but it will avoid clipping the negatives to -inf.

My hesitation with (1) is that it overlaps a lot with (2) but then loses my guarantee of 0.0 linear not being moved by an offset adjustment, and it means that the log conversion has more than a single parameter--the number of stops between 0 and 1. If you don't really care for this requirement, maybe one of the log spaces with a toe would be the preferable working space. On the topic of (3), honestly I mostly made this DCTL because I wanted to use the RGB curves tool in Resolve and be able to make photometric adjustments via addition, so neither of those tools should be broken here. What tools are you using in step (3) that you're running into problems with? If they're mine, maybe I can fix those issues with those tools or evaluate if T-Log is the right domain for them in the first place.

To answer your question, clamping the linear values would be like a three or four line code change on my end and would not be difficult to implement. My only qualm really is that I'm not entirely sure whether it is the right design choice, which is why I want to know more about the specific problems you're running into. If it were up to me, the ideal solution would be if we had the capability to use imaginary numbers, in which case I would probably modify the tool to map negative linear values to the imaginary component. As much as I'd like that feature, I don't think it'll ever come to Resolve, though we could hack it in if they made it so DCTLs could have multiple inputs.

**Comment by antonmeleshkevich** [comment]
Thank you for the most detailed response I could think of!
I usually work in linear domain as much as possible. I tried earlier to work using ACEScc, but there were some downsides with spatial adjustments like gaussian blur (or sharpness, it was a couple of years ago, so I'm not sure).
So I'm mostly interested in using true log space for things like keyer or RGB curves for split-toning using offset and gain wheels. But it turned out that this is identical to split-toning using per-channel power function with some adjustable pivot.
It's more of "what else I can do using true log spaces?" kind of thing. Trying to simplify my workflow using photometric adjustments as much as possible.
So you definitely don't need to rewrite anything just for me, it's maybe more my OCD, than the actual need I think :)
Just wanted to mention this -inf thing in case it wasn't intentional there.
I wish one day Resolve would let us to rewrite their wheels and knobs using custom DCTL code. So many things have to be fixed or improved there! Even for black offset in HDR palette they don't do it the most simple and the most correct way - addition in linear domain, but something way worse instead.

**Comment by thatcherfreeman** [comment]
Good thinking, imo the main use-case for nonlinear spaces such as this t-log is for keyers, RGB curve adjustments, and for edge detection (blurring in linear expands the highlights rather than preserving the edge positions). For the most part, almost everything else I do is in linear too
