### ISSUE TITLE
Dye Sim not working

### ISSUE THREAD

**Issue by robynsun-love** [thatcherfreeman/utility-dctls#9]
Hello!

I just downloaded the updated version of your Dye Simulator DCTL (from commit no. 9918e12), only to find that it was not working properly. All the UI params showed up just fine, but neither the dye density nor observer charts appeared when turned on, and the entire screen was rendered black (surrounded by a tiny white border, as if the whole screen had a negative value - for the hell of it, in the next node I raised the offset by 1000, only to find zero change to the image.)

I use your DCTLs through your DCTL Interpreter Fuse; and the "Explicitly Typecast Built-In Functions" button in Fusion's Inspector tab (which I find helps certain DCTLs run properly) did nothing to help here.

I redownloaded an older version of the DCTL (commit no. 2a18759) to check - and sure enough, it works fine. The issue must be from commit no. 9918e12.

P.S. what were the dimensions of the image you were using when you created/tested the DCTL? The charts rescale depending on the size of the image, making using them quite frustrating 😅

**Comment by thatcherfreeman** [comment]
Can you describe your OS and system specs? Cuda or OpenCL or metal?

**Comment by thatcherfreeman** [comment]
Ok looks like I was able to reproduce the issues on OpenCL. I've made adjustments to most of my DCTLs to improve OpenCL compatibility, so go ahead and redownload the dye simulator and it should work for you.

A couple further notes:
1. In OpenCL, the DCTL Interpreter Fuse currently can't run DCTLs that require sampling other pixels in the frame. This is because OpenCL has restrictions on how you can use the `__TEXTURE__` type that is broken with the way I ported those over to the Fuse DCTL variant.
2. Please just switch to CUDA or Metal if you can. Nobody tests their DCTLs on OpenCL because most Resolve users have an Nvidia GPU or a macbook, and in either platform CUDA or Metal are the preferred systems. Most code works just as well on both of those platforms and it's OpenCL that has a bunch of problems where it can't run code that works fine on other platforms.
